# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affidavit',
            name='body',
        ),
        migrations.AddField(
            model_name='affidavit',
            name='name',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
    ]
