# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180815_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandletter',
            name='doc',
        ),
        migrations.AlterField(
            model_name='demandletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legals', to='review.Profile'),
        ),
    ]
