# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180815_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandletter',
            name='body',
        ),
        migrations.RemoveField(
            model_name='demandletter',
            name='title',
        ),
        migrations.AddField(
            model_name='demandletter',
            name='boxnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='firstname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='idnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='othernames',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='sirname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='town',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
