# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_remove_demandletter_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='test', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(default='00000000'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='test', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default='0700000000'),
        ),
    ]
