# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_remove_demandletter_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavit',
            name='unique_key',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandletter',
            name='unique_key',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
