# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20180828_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='boxnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='othernames',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phione_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sirname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
