# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_remove_affidavit_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandletter',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
